[package]
name = "ga_engine"
version = "0.1.0"
edition = "2024"

[dependencies]
engine_core = { path = "engine_core" }
rand = "0.9.2"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.142"

[profile.dev]
debug = true
