[package]
name = "engine_core"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["lib"]
path = "src/core.rs"

[dependencies]
chrono = { version = "0.4.41", features = ["serde"] }
rand = "0.9.2"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.142"
